# Generated by Django 5.0.6 on 2024-06-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_agent_created_by_agent_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
