# Generated by Django 5.0.6 on 2024-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_agent_default_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
