# Generated by Django 5.0.6 on 2024-06-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_agent_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_no',
            field=models.CharField(default=None, max_length=20, null = True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
            preserve_default=False,
        ),
    ]
