# Generated by Django 5.0.6 on 2024-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_admission_commission_rate_admission_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True),
        ),
    ]
